# Generated by Django 5.2.1 on 2025-05-30 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_es', models.CharField(max_length=100, verbose_name='Name (Spanish)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=200, verbose_name='Title (Spanish)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_es', models.TextField(verbose_name='Description (Spanish)')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('online', models.BooleanField(default=False, verbose_name='Online Event')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Meeting Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=200, verbose_name='Title (Spanish)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_es', models.TextField(verbose_name='Description (Spanish)')),
                ('link', models.URLField(blank=True, verbose_name='External Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.category')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='es', max_length=2, verbose_name='Preferred Language')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Country of Origin')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
