# Generated by Django 5.2.4 on 2025-09-18 10:19

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_es', models.CharField(max_length=100, verbose_name='Name (Spanish)')),
                ('title', models.CharField(max_length=200, verbose_name='Professional Title')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=200, verbose_name='Title (Spanish)')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('bio_en', models.TextField(blank=True, verbose_name='Biography (English)')),
                ('bio_es', models.TextField(blank=True, verbose_name='Biography (Spanish)')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('photo', models.ImageField(blank=True, help_text='Recommended size: 300x300 pixels (square)', null=True, upload_to=core.models.staff_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Profile Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('show_on_contact_page', models.BooleanField(default=False, verbose_name='Show on Contact Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
